In [4]:
# NumPy

# shape - row, column
# ndim - number dimensions 
# itemsize - size in bytes (divided by 8)
# size 
# dtype.name - datatype

import numpy as np

a = np.arange(15).reshape(3, 5)
a.shape

15

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.size

15

In [8]:
a.itemsize

8

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
b.size

3

In [12]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
np.ones((3, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty((2,3))

array([[-2.31584178e+077, -2.31584178e+077,  2.47032823e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [18]:
np.empty((2,3))

array([[-2.31584178e+077, -2.31584178e+077,  2.47032823e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])